<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database with realistic executive data.
     */
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('payments')->truncate();
        DB::table('order_items')->truncate();
        DB::table('orders')->truncate();
        DB::table('invoices')->truncate();
        DB::table('harvest_batches')->truncate();
        DB::table('contracts')->truncate();
        DB::table('products')->truncate();
        DB::table('users')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        // Kata sandi default untuk seluruh akun pengujian: password123
        $defaultPassword = Hash::make('password123');

        // =====================================================================
        // 1. SEED USERS (Aktor Internal & Klien B2B Kemitraan)
        // =====================================================================
        DB::table('users')->insert([
            // 1. Direktur Utama (DIR-01 / Owner)
            [
                'id' => 1,
                'name' => 'Ahmad Sanusi, S.P.',
                'email' => 'direktur@greenpasundan.id',
                'phone' => '081112233445',
                'password' => $defaultPassword,
                'role' => 'DIREKTUR',
                'client_type' => null,
                'company_name' => 'Koperasi Green Pasundan Agriculture (Ciwidey)',
                'address' => 'Komplek Griya Pasundan Asri No. 01, Soreang, Bandung',
                'pic_name' => 'Ahmad Sanusi',
                'pic_phone' => '081112233445',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 2. Head of Finance & Sekretaris
            [
                'id' => 2,
                'name' => 'Nurhayati, S.Ak',
                'email' => 'sekre@greenpasundan.id',
                'phone' => '085220001122',
                'password' => $defaultPassword,
                'role' => 'SEKRETARIS',
                'client_type' => null,
                'company_name' => 'Kantor Pusat GPA Ciwidey',
                'address' => 'Kantor Operasional GPA, Desa Panundaan, Ciwidey',
                'pic_name' => 'Nurhayati',
                'pic_phone' => '085220001122',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 3. Staf Administrasi Sekretariat
            [
                'id' => 3,
                'name' => 'Rina Marlina',
                'email' => 'rina.sekre@greenpasundan.id',
                'phone' => '085220009988',
                'password' => $defaultPassword,
                'role' => 'SEKRETARIS',
                'client_type' => null,
                'company_name' => 'Kantor Pusat GPA Ciwidey',
                'address' => 'Kantor Operasional GPA, Desa Panundaan, Ciwidey',
                'pic_name' => 'Rina Marlina',
                'pic_phone' => '085220009988',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 4. Koordinator Lapangan Utama (STA & Timbangan)
            [
                'id' => 4,
                'name' => 'Agung Wicaksono',
                'email' => 'koordinator@greenpasundan.id',
                'phone' => '081334455667',
                'password' => $defaultPassword,
                'role' => 'KOORDINATOR',
                'client_type' => null,
                'company_name' => 'Gudang Konsolidasi GPA STA Lembang',
                'address' => 'Packing House GPA, RT 03/RW 02 Panundaan, Ciwidey',
                'pic_name' => 'Agung Wicaksono',
                'pic_phone' => '081334455667',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 5. Koordinator Lapangan Kebun Binaan
            [
                'id' => 5,
                'name' => 'Asep Sunandar',
                'email' => 'asep.lapangan@greenpasundan.id',
                'phone' => '081334455888',
                'password' => $defaultPassword,
                'role' => 'KOORDINATOR',
                'client_type' => null,
                'company_name' => 'Kebun Binaan Rancabali',
                'address' => 'Sentra Produksi Rancabali, Ciwidey',
                'pic_name' => 'Asep Sunandar',
                'pic_phone' => '081334455888',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 6. Armada Driver Reefer Logistik
            [
                'id' => 6,
                'name' => 'Joko Prasetyo',
                'email' => 'armada@greenpasundan.id',
                'phone' => '087889900112',
                'password' => $defaultPassword,
                'role' => 'ARMADA',
                'client_type' => null,
                'company_name' => 'Armada Logistik Pendingin GPA',
                'address' => 'Pangkalan Armada GPA, Jl. Raya Soreang-Ciwidey Km 4',
                'pic_name' => 'Joko Prasetyo',
                'pic_phone' => '087889900112',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 7. Armada Driver Cadangan
            [
                'id' => 7,
                'name' => 'Ujang Koswara',
                'email' => 'ujang.supir@greenpasundan.id',
                'phone' => '087889900333',
                'password' => $defaultPassword,
                'role' => 'ARMADA',
                'client_type' => null,
                'company_name' => 'Armada Logistik Pendingin GPA',
                'address' => 'Pangkalan Armada GPA, Jl. Raya Soreang-Ciwidey Km 4',
                'pic_name' => 'Ujang Koswara',
                'pic_phone' => '087889900333',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 8. KLIEN B2B: PT Aerofood ACS Indonesia (Inflight Catering)
            [
                'id' => 8,
                'name' => 'PT Aerofood ACS Indonesia',
                'email' => 'aerofood@client.id',
                'phone' => '0215501234',
                'password' => $defaultPassword,
                'role' => 'KLIEN',
                'client_type' => 'B2B_KONTRAK',
                'company_name' => 'PT Aerofood ACS Indonesia (Hub Soekarno-Hatta)',
                'address' => 'Area Bandara Internasional Soekarno-Hatta, Tangerang, Banten',
                'pic_name' => 'Chef Ridwan S.',
                'pic_phone' => '081288990011',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 9. KLIEN B2B: Hotel Grand Pangrango Bogor (Horeca)
            [
                'id' => 9,
                'name' => 'Hotel Grand Pangrango',
                'email' => 'grandpangrango@client.id',
                'phone' => '02518321234',
                'password' => $defaultPassword,
                'role' => 'KLIEN',
                'client_type' => 'B2B_KONTRAK',
                'company_name' => 'Hotel Grand Pangrango Bogor',
                'address' => 'Jl. Raya Pajajaran No. 28, Kota Bogor, Jawa Barat',
                'pic_name' => 'Suryana, SE (Purchasing)',
                'pic_phone' => '081399887766',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 10. KLIEN B2B: PT Boga Rasa Kulina Prima (Resto Chain)
            [
                'id' => 10,
                'name' => 'PT Boga Rasa Kulina Prima',
                'email' => 'bogarasa@client.id',
                'phone' => '0213890123',
                'password' => $defaultPassword,
                'role' => 'KLIEN',
                'client_type' => 'B2B_KONTRAK',
                'company_name' => 'PT Boga Rasa Kulina Prima (14 Outlets)',
                'address' => 'Kawasan Industri Pulogadung Blok B No. 4, Jakarta Timur',
                'pic_name' => 'Maya Hartono',
                'pic_phone' => '081766554433',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 11. KLIEN B2B: PT Segar Makmur Ritelindo (Modern Retail)
            [
                'id' => 11,
                'name' => 'PT Segar Makmur Ritelindo',
                'email' => 'segarmakmur@client.id',
                'phone' => '0217890456',
                'password' => $defaultPassword,
                'role' => 'KLIEN',
                'client_type' => 'B2B_KONTRAK',
                'company_name' => 'PT Segar Makmur Ritelindo',
                'address' => 'Central DC Cikarang Dry Port, Bekasi',
                'pic_name' => 'Doni Setiawan',
                'pic_phone' => '081512345678',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 12. KLIEN B2B: CV Mitra Boga Nusantara
            [
                'id' => 12,
                'name' => 'CV Mitra Boga Nusantara',
                'email' => 'mitraboga@client.id',
                'phone' => '0228765432',
                'password' => $defaultPassword,
                'role' => 'KLIEN',
                'client_type' => 'B2B_KONTRAK',
                'company_name' => 'CV Mitra Boga Nusantara (Katering Industri)',
                'address' => 'Kawasan Industri Cimareme No. 18, Padalarang, Bandung Barat',
                'pic_name' => 'Rudi Hartono',
                'pic_phone' => '081234567890',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 13. KLIEN B2B: Resto Dapur Sunda Asli
            [
                'id' => 13,
                'name' => 'Resto Dapur Sunda Asli',
                'email' => 'dapursunda@client.id',
                'phone' => '0222019988',
                'password' => $defaultPassword,
                'role' => 'KLIEN',
                'client_type' => 'B2B_KONTRAK',
                'company_name' => 'Resto Dapur Sunda Asli (Jaringan 4 Cabang)',
                'address' => 'Jl. Dr. Setiabudi No. 102, Kota Bandung',
                'pic_name' => 'Ibu Ratna Sari',
                'pic_phone' => '081320203040',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 14. KLIEN B2B: PT AEON Indonesia
            [
                'id' => 14,
                'name' => 'PT AEON Indonesia',
                'email' => 'dewi.purchasing@aeon.co.id',
                'phone' => '08122334455',
                'password' => $defaultPassword,
                'role' => 'KLIEN',
                'client_type' => 'B2B_KONTRAK',
                'company_name' => 'PT AEON Indonesia (BSD & JGC Store)',
                'address' => 'AEON Mall BSD City, Jl. BSD Raya Utama, Tangerang',
                'pic_name' => 'Dewi Anggraeni',
                'pic_phone' => '08122334455',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 15. KLIEN REGULER: CV Barokah Kuliner Bandung
            [
                'id' => 15,
                'name' => 'Pak Hendra Pratama',
                'email' => 'hendra@kateringbarokah.com',
                'phone' => '08198765432',
                'password' => $defaultPassword,
                'role' => 'KLIEN',
                'client_type' => 'REGULER',
                'company_name' => 'CV Barokah Kuliner Bandung',
                'address' => 'Jl. Buah Batu No. 142, Kota Bandung',
                'pic_name' => 'Hendra Pratama',
                'pic_phone' => '08198765432',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // =====================================================================
        // 2. SEED PRODUCTS (5 Komoditas Inti Standar Metrologi GPA)
        // =====================================================================
        DB::table('products')->insert([
            [
                'id' => 1,
                'sku' => 'GPA-VGT-RMN01',
                'name' => 'Selada Romaine Hydroponic Super',
                'unit' => 'kg',
                'grade' => 'Grade A',
                'base_price' => 14500.00,
                'minimum_order' => 10.00,
                'image_url' => 'products/selada.jpg',
                'description' => 'Selada romaine segar renyah hidroponik dataran tinggi Ciwidey, bebas residu pestisida.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'sku' => 'GPA-VGT-BRK02',
                'name' => 'Brokoli Super Lembang',
                'unit' => 'kg',
                'grade' => 'Grade A',
                'base_price' => 22000.00,
                'minimum_order' => 5.00,
                'image_url' => 'products/brokoli.jpg',
                'description' => 'Kuntum brokoli hijau padat tanpa ulat, pemetikan pagi hari dari kebun binaan Lembang.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'sku' => 'GPA-FRT-TMT03',
                'name' => 'Tomat Beef Garut & Sayur',
                'unit' => 'kg',
                'grade' => 'Grade A',
                'base_price' => 16000.00,
                'minimum_order' => 5.00,
                'image_url' => 'products/tomat.jpg',
                'description' => 'Tomat beef berdaging padat dan tebal dari sentra greenhouse Garut.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'sku' => 'GPA-BER-STR04',
                'name' => 'Stroberi Ciwidey Sweet Grade',
                'unit' => 'pack',
                'grade' => 'Grade A',
                'base_price' => 25000.00,
                'minimum_order' => 2.00,
                'image_url' => 'products/stroberi.jpg',
                'description' => 'Stroberi manis petik langsung dari petani lokal Ciwidey kemasan mika pack 500 gram higienis.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'sku' => 'GPA-VGT-KOL05',
                'name' => 'Kol Putih Organik Pangalengan',
                'unit' => 'kg',
                'grade' => 'Grade A',
                'base_price' => 8000.00,
                'minimum_order' => 10.00,
                'image_url' => 'products/kol.jpg',
                'description' => 'Kol putih krop bulat padat berserat halus standar pasokan supermarket.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // =====================================================================
        // 3. SEED CONTRACTS (Kontrak B2B: Pending Approval & Aktif)
        // =====================================================================
        DB::table('contracts')->insert([
            // 3 Kontrak Pending Otorisasi Direktur Utama (Sesuai UI/UX PDF)
            [
                'id' => 1,
                'user_id' => 9, // Hotel Grand Pangrango
                'product_id' => 1, // Selada Romaine
                'contract_number' => 'CTR-B2B-2025-089',
                'fixed_price_per_kg' => 13800.00,
                'top_days' => 30,
                'committed_volume_per_cycle' => 3200.00,
                'status' => 'PENDING_APPROVAL',
                'approved_by' => null,
                'approved_at' => null,
                'created_at' => '2026-10-10 09:15:00',
                'updated_at' => '2026-10-10 09:15:00',
            ],
            [
                'id' => 2,
                'user_id' => 10, // PT Boga Rasa Kulina Prima
                'product_id' => 3, // Tomat Beef
                'contract_number' => 'CTR-B2B-2025-092',
                'fixed_price_per_kg' => 15000.00,
                'top_days' => 45,
                'committed_volume_per_cycle' => 5000.00,
                'status' => 'PENDING_APPROVAL',
                'approved_by' => null,
                'approved_at' => null,
                'created_at' => '2026-10-12 11:30:00',
                'updated_at' => '2026-10-12 11:30:00',
            ],
            [
                'id' => 3,
                'user_id' => 8, // PT Aerofood ACS Indonesia
                'product_id' => 2, // Brokoli Super
                'contract_number' => 'CTR-B2B-2025-095',
                'fixed_price_per_kg' => 18000.00,
                'top_days' => 30,
                'committed_volume_per_cycle' => 4000.00,
                'status' => 'PENDING_APPROVAL',
                'approved_by' => null,
                'approved_at' => null,
                'created_at' => '2026-10-13 14:00:00',
                'updated_at' => '2026-10-13 14:00:00',
            ],
            // Kontrak Aktif B2B
            [
                'id' => 4,
                'user_id' => 8, // PT Aerofood ACS Indonesia
                'product_id' => 1, // Selada Romaine
                'contract_number' => 'KTR-2026-ACS-001',
                'fixed_price_per_kg' => 14000.00,
                'top_days' => 45,
                'committed_volume_per_cycle' => 14200.00,
                'status' => 'ACTIVE',
                'approved_by' => 1,
                'approved_at' => '2026-08-01 08:30:00',
                'created_at' => '2026-08-01 08:00:00',
                'updated_at' => '2026-08-01 08:30:00',
            ],
            [
                'id' => 5,
                'user_id' => 9, // Hotel Grand Pangrango
                'product_id' => 3, // Tomat Beef
                'contract_number' => 'KTR-2026-HGP-004',
                'fixed_price_per_kg' => 15500.00,
                'top_days' => 30,
                'committed_volume_per_cycle' => 9600.00,
                'status' => 'ACTIVE',
                'approved_by' => 1,
                'approved_at' => '2026-08-15 09:00:00',
                'created_at' => '2026-08-15 08:30:00',
                'updated_at' => '2026-08-15 09:00:00',
            ],
            [
                'id' => 6,
                'user_id' => 10, // PT Boga Rasa Kulina Prima
                'product_id' => 2, // Brokoli Super
                'contract_number' => 'KTR-2026-BRK-007',
                'fixed_price_per_kg' => 21000.00,
                'top_days' => 30,
                'committed_volume_per_cycle' => 7200.00,
                'status' => 'ACTIVE',
                'approved_by' => 1,
                'approved_at' => '2026-08-20 10:00:00',
                'created_at' => '2026-08-20 09:00:00',
                'updated_at' => '2026-08-20 10:00:00',
            ],
            [
                'id' => 7,
                'user_id' => 11, // PT Segar Makmur Ritelindo
                'product_id' => 5, // Kol Putih
                'contract_number' => 'KTR-2026-SMR-019',
                'fixed_price_per_kg' => 7500.00,
                'top_days' => 14,
                'committed_volume_per_cycle' => 11200.00,
                'status' => 'ACTIVE',
                'approved_by' => 1,
                'approved_at' => '2026-09-01 11:00:00',
                'created_at' => '2026-09-01 10:00:00',
                'updated_at' => '2026-09-01 11:00:00',
            ],
            [
                'id' => 8,
                'user_id' => 13, // Resto Dapur Sunda Asli
                'product_id' => 1, // Selada Romaine
                'contract_number' => 'KTR-2026-DSA-019',
                'fixed_price_per_kg' => 14200.00,
                'top_days' => 14,
                'committed_volume_per_cycle' => 7200.00,
                'status' => 'ACTIVE',
                'approved_by' => 1,
                'approved_at' => '2026-09-05 13:00:00',
                'created_at' => '2026-09-05 12:00:00',
                'updated_at' => '2026-09-05 13:00:00',
            ],
            [
                'id' => 9,
                'user_id' => 12, // CV Mitra Boga Nusantara
                'product_id' => 3, // Tomat Beef
                'contract_number' => 'KTR-2026-MBN-008',
                'fixed_price_per_kg' => 15000.00,
                'top_days' => 30,
                'committed_volume_per_cycle' => 8400.00,
                'status' => 'ACTIVE',
                'approved_by' => 1,
                'approved_at' => '2026-09-10 14:00:00',
                'created_at' => '2026-09-10 13:00:00',
                'updated_at' => '2026-09-10 14:00:00',
            ],
            [
                'id' => 10,
                'user_id' => 14, // PT AEON Indonesia
                'product_id' => 4, // Stroberi Ciwidey
                'contract_number' => 'CTR-GPA-202609-0001',
                'fixed_price_per_kg' => 24000.00,
                'top_days' => 30,
                'committed_volume_per_cycle' => 4500.00,
                'status' => 'ACTIVE',
                'approved_by' => 1,
                'approved_at' => '2026-09-01 08:30:00',
                'created_at' => '2026-09-01 08:00:00',
                'updated_at' => '2026-09-01 08:30:00',
            ],
        ]);

        // =====================================================================
        // 4. SEED HARVEST BATCHES (Rasio Pasokan Petani Binaan vs Buffer Luar)
        // =====================================================================
        DB::table('harvest_batches')->insert([
            // Komoditas 1: Selada Romaine (Binaan: 18000 kg, Buffer: 3710 kg)
            [
                'id' => 1,
                'product_id' => 1,
                'source_type' => 'PETANI_BINAAN',
                'supplier_name' => 'Kelompok Tani Hidroponik Panundaan',
                'batch_date' => '2026-10-01',
                'initial_quantity' => 18000.00,
                'available_quantity' => 1450.00,
                'inputted_by' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'product_id' => 1,
                'source_type' => 'BUFFER_LUAR',
                'supplier_name' => 'Mitra Cadangan Rancabali Hub',
                'batch_date' => '2026-10-05',
                'initial_quantity' => 3710.00,
                'available_quantity' => 800.00,
                'inputted_by' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Komoditas 2: Brokoli Super (Binaan: 6100 kg, Buffer: 1140 kg)
            [
                'id' => 3,
                'product_id' => 2,
                'source_type' => 'PETANI_BINAAN',
                'supplier_name' => 'Gapoktan Sayur Lembang Dataran Tinggi',
                'batch_date' => '2026-10-02',
                'initial_quantity' => 6100.00,
                'available_quantity' => 480.00,
                'inputted_by' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'product_id' => 2,
                'source_type' => 'BUFFER_LUAR',
                'supplier_name' => 'Mitra Tani Sejahtera Parongpong',
                'batch_date' => '2026-10-04',
                'initial_quantity' => 1140.00,
                'available_quantity' => 210.00,
                'inputted_by' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Komoditas 3: Tomat Beef (Binaan: 9800 kg, Buffer: 2260 kg)
            [
                'id' => 5,
                'product_id' => 3,
                'source_type' => 'PETANI_BINAAN',
                'supplier_name' => 'Sentra Greenhouse Garut Tarogong',
                'batch_date' => '2026-10-03',
                'initial_quantity' => 9800.00,
                'available_quantity' => 820.00,
                'inputted_by' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'product_id' => 3,
                'source_type' => 'BUFFER_LUAR',
                'supplier_name' => 'Mitra Cadangan Cikajang Garut',
                'batch_date' => '2026-10-06',
                'initial_quantity' => 2260.00,
                'available_quantity' => 350.00,
                'inputted_by' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Komoditas 4: Stroberi Ciwidey (Binaan: 3900 kg, Buffer: 930 kg)
            [
                'id' => 7,
                'product_id' => 4,
                'source_type' => 'PETANI_BINAAN',
                'supplier_name' => 'Kelompok Tani Stroberi Alamendah',
                'batch_date' => '2026-10-05',
                'initial_quantity' => 3900.00,
                'available_quantity' => 210.00,
                'inputted_by' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'product_id' => 4,
                'source_type' => 'BUFFER_LUAR',
                'supplier_name' => 'Mitra Buffer Patuha Ciwidey',
                'batch_date' => '2026-10-07',
                'initial_quantity' => 930.00,
                'available_quantity' => 95.00,
                'inputted_by' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Komoditas 5: Kol Putih Organik (Binaan: 2200 kg, Buffer: 210 kg)
            [
                'id' => 9,
                'product_id' => 5,
                'source_type' => 'PETANI_BINAAN',
                'supplier_name' => 'Gapoktan Organik Pangalengan Lestari',
                'batch_date' => '2026-10-04',
                'initial_quantity' => 2200.00,
                'available_quantity' => 600.00,
                'inputted_by' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'product_id' => 5,
                'source_type' => 'BUFFER_LUAR',
                'supplier_name' => 'Mitra Kebun Situ Cileunca',
                'batch_date' => '2026-10-08',
                'initial_quantity' => 210.00,
                'available_quantity' => 50.00,
                'inputted_by' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // =====================================================================
        // 5. SEED INVOICES (Faktur Tempo & Piutang Berjalan - Aging AR)
        // =====================================================================
        DB::table('invoices')->insert([
            // STAGE 01 (0-15 HARI TERSISA): PT Aerofood ACS Indonesia (Lancar / In-Schedule)
            [
                'id' => 1,
                'invoice_number' => 'INV-GPA-202610-0088',
                'user_id' => 8,
                'period_start' => '2026-10-01',
                'period_end' => '2026-10-15',
                'subtotal_amount' => 114200000.00,
                'grand_total' => 114200000.00,
                'due_date' => now()->addDays(22)->toDateString(), // 22 hari tersisa
                'status' => 'UNPAID',
                'pdf_file_path' => 'invoices/INV-GPA-202610-0088.pdf',
                'created_at' => '2026-10-15 10:00:00',
                'updated_at' => '2026-10-15 10:00:00',
            ],
            // STAGE 02 (16-30 HARI / MENDEKATI TEMPO <7 HARI): Hotel Grand Pangrango
            [
                'id' => 2,
                'invoice_number' => 'INV-GPA-202609-0064',
                'user_id' => 9,
                'period_start' => '2026-09-15',
                'period_end' => '2026-09-30',
                'subtotal_amount' => 59550000.00,
                'grand_total' => 59550000.00,
                'due_date' => now()->addDays(3)->toDateString(), // H-3 Jatuh Tempo
                'status' => 'UNPAID',
                'pdf_file_path' => 'invoices/INV-GPA-202609-0064.pdf',
                'created_at' => '2026-09-30 11:00:00',
                'updated_at' => '2026-09-30 11:00:00',
            ],
            // STAGE 03 (LEWAT TEMPO 1-14 HARI): PT Boga Rasa Kulina Prima
            [
                'id' => 3,
                'invoice_number' => 'INV-GPA-202609-0082',
                'user_id' => 10,
                'period_start' => '2026-09-01',
                'period_end' => '2026-09-20',
                'subtotal_amount' => 56750000.00,
                'grand_total' => 56750000.00,
                'due_date' => now()->subDays(5)->toDateString(), // Overdue 5 Hari
                'status' => 'OVERDUE',
                'pdf_file_path' => 'invoices/INV-GPA-202609-0082.pdf',
                'created_at' => '2026-09-20 14:00:00',
                'updated_at' => '2026-09-20 14:00:00',
            ],
            // STAGE 04 (OVERDUE KRITIS >15 HARI / AUTO-FREEZE PO): PT Segar Makmur Ritelindo
            [
                'id' => 4,
                'invoice_number' => 'INV-GPA-202609-0032',
                'user_id' => 11,
                'period_start' => '2026-08-25',
                'period_end' => '2026-09-10',
                'subtotal_amount' => 18000000.00,
                'grand_total' => 18000000.00,
                'due_date' => now()->subDays(18)->toDateString(), // Overdue 18 Hari
                'status' => 'OVERDUE',
                'pdf_file_path' => 'invoices/INV-GPA-202609-0032.pdf',
                'created_at' => '2026-09-10 15:00:00',
                'updated_at' => '2026-09-10 15:00:00',
            ],
            // FAKTUR TUNTAS TERBAYAR (CASH INFLOW REALISASI)
            [
                'id' => 5,
                'invoice_number' => 'INV-GPA-202608-0010',
                'user_id' => 8, // Aerofood
                'period_start' => '2026-08-01',
                'period_end' => '2026-08-31',
                'subtotal_amount' => 146160000.00,
                'grand_total' => 146160000.00,
                'due_date' => '2026-09-30',
                'status' => 'PAID',
                'pdf_file_path' => 'invoices/INV-GPA-202608-0010.pdf',
                'created_at' => '2026-08-31 16:00:00',
                'updated_at' => '2026-09-25 10:00:00',
            ],
            [
                'id' => 6,
                'invoice_number' => 'INV-GPA-202608-0011',
                'user_id' => 9, // Grand Pangrango
                'period_start' => '2026-08-01',
                'period_end' => '2026-08-31',
                'subtotal_amount' => 107980000.00,
                'grand_total' => 107980000.00,
                'due_date' => '2026-09-30',
                'status' => 'PAID',
                'pdf_file_path' => 'invoices/INV-GPA-202608-0011.pdf',
                'created_at' => '2026-08-31 16:30:00',
                'updated_at' => '2026-09-28 11:00:00',
            ],
            [
                'id' => 7,
                'invoice_number' => 'INV-GPA-202608-0012',
                'user_id' => 13, // Dapur Sunda
                'period_start' => '2026-08-15',
                'period_end' => '2026-09-15',
                'subtotal_amount' => 80180000.00,
                'grand_total' => 80180000.00,
                'due_date' => '2026-09-30',
                'status' => 'PAID',
                'pdf_file_path' => 'invoices/INV-GPA-202608-0012.pdf',
                'created_at' => '2026-09-15 17:00:00',
                'updated_at' => '2026-09-29 14:00:00',
            ],
            [
                'id' => 8,
                'invoice_number' => 'INV-GPA-202608-0013',
                'user_id' => 14, // AEON
                'period_start' => '2026-08-01',
                'period_end' => '2026-08-31',
                'subtotal_amount' => 74010000.00,
                'grand_total' => 74010000.00,
                'due_date' => '2026-09-30',
                'status' => 'PAID',
                'pdf_file_path' => 'invoices/INV-GPA-202608-0013.pdf',
                'created_at' => '2026-08-31 17:30:00',
                'updated_at' => '2026-09-30 16:00:00',
            ],
        ]);

        // =====================================================================
        // 6. SEED ORDERS (Pesanan Riil Sesuai Transaksi & Surat Jalan)
        // =====================================================================
        DB::table('orders')->insert([
            // Order 1: Aerofood ACS (SJ-088)
            [
                'id' => 1,
                'order_number' => 'ORD-GPA-202610-0088',
                'user_id' => 8,
                'invoice_id' => 1,
                'order_source' => 'ROUTINE_SCHEDULE',
                'target_delivery_date' => now()->subDays(2)->toDateString(),
                'delivery_address' => 'Loading Dock Bandara Soekarno-Hatta Hub',
                'estimated_total' => 114500000.00,
                'grand_total' => 114200000.00,
                'status' => 'SELESAI',
                'verified_by' => 2,
                'surat_jalan_number' => 'SJ-088',
                'driver_id' => 6,
                'vehicle_plate_number' => 'B 9014 KPA',
                'departure_time' => now()->subDays(2)->setTime(5, 0),
                'arrival_time' => now()->subDays(2)->setTime(8, 30),
                'pod_photo_url' => 'pod/pod_sj_088.jpg',
                'received_by_name' => 'Chef Ridwan (QC Aerofood)',
                'created_at' => now()->subDays(4),
                'updated_at' => now()->subDays(2),
            ],
            // Order 2: Grand Pangrango (SJ-064)
            [
                'id' => 2,
                'order_number' => 'ORD-GPA-202609-0064',
                'user_id' => 9,
                'invoice_id' => 2,
                'order_source' => 'WEB_PORTAL',
                'target_delivery_date' => now()->subDays(6)->toDateString(),
                'delivery_address' => 'Gudang Basah Hotel Grand Pangrango Bogor',
                'estimated_total' => 60000000.00,
                'grand_total' => 59550000.00,
                'status' => 'SELESAI',
                'verified_by' => 2,
                'surat_jalan_number' => 'SJ-064',
                'driver_id' => 6,
                'vehicle_plate_number' => 'B 9014 KPA',
                'departure_time' => now()->subDays(6)->setTime(4, 30),
                'arrival_time' => now()->subDays(6)->setTime(7, 45),
                'pod_photo_url' => 'pod/pod_sj_064.jpg',
                'received_by_name' => 'Pak Suryana',
                'created_at' => now()->subDays(8),
                'updated_at' => now()->subDays(6),
            ],
            // Order 3: PT Boga Rasa Kulina Prima (SJ-082)
            [
                'id' => 3,
                'order_number' => 'ORD-GPA-202609-0082',
                'user_id' => 10,
                'invoice_id' => 3,
                'order_source' => 'ROUTINE_SCHEDULE',
                'target_delivery_date' => now()->subDays(10)->toDateString(),
                'delivery_address' => 'Kawasan Industri Pulogadung Blok B No. 4, Jakarta Timur',
                'estimated_total' => 57000000.00,
                'grand_total' => 56750000.00,
                'status' => 'SELESAI',
                'verified_by' => 2,
                'surat_jalan_number' => 'SJ-082',
                'driver_id' => 7,
                'vehicle_plate_number' => 'D 8124 AB',
                'departure_time' => now()->subDays(10)->setTime(4, 0),
                'arrival_time' => now()->subDays(10)->setTime(8, 0),
                'pod_photo_url' => 'pod/pod_sj_082.jpg',
                'received_by_name' => 'Ibu Maya Hartono',
                'created_at' => now()->subDays(12),
                'updated_at' => now()->subDays(10),
            ],
            // Order 4: PT Segar Makmur Ritelindo (SJ-032)
            [
                'id' => 4,
                'order_number' => 'ORD-GPA-202609-0032',
                'user_id' => 11,
                'invoice_id' => 4,
                'order_source' => 'WEB_PORTAL',
                'target_delivery_date' => now()->subDays(20)->toDateString(),
                'delivery_address' => 'Central DC Cikarang Dry Port, Bekasi',
                'estimated_total' => 18000000.00,
                'grand_total' => 18000000.00,
                'status' => 'SELESAI',
                'verified_by' => 2,
                'surat_jalan_number' => 'SJ-032',
                'driver_id' => 6,
                'vehicle_plate_number' => 'B 9014 KPA',
                'departure_time' => now()->subDays(20)->setTime(5, 30),
                'arrival_time' => now()->subDays(20)->setTime(9, 15),
                'pod_photo_url' => 'pod/pod_sj_032.jpg',
                'received_by_name' => 'Doni Setiawan',
                'created_at' => now()->subDays(22),
                'updated_at' => now()->subDays(20),
            ],
            // Order 5: Aerofood Settled Inflow (SJ-010)
            [
                'id' => 5,
                'order_number' => 'ORD-GPA-202608-0010',
                'user_id' => 8,
                'invoice_id' => 5,
                'order_source' => 'ROUTINE_SCHEDULE',
                'target_delivery_date' => '2026-08-25',
                'delivery_address' => 'Hub Soekarno Hatta',
                'estimated_total' => 146160000.00,
                'grand_total' => 146160000.00,
                'status' => 'SELESAI',
                'verified_by' => 2,
                'surat_jalan_number' => 'SJ-010',
                'driver_id' => 6,
                'vehicle_plate_number' => 'B 9014 KPA',
                'departure_time' => '2026-08-25 04:30:00',
                'arrival_time' => '2026-08-25 08:00:00',
                'pod_photo_url' => 'pod/pod_sj_010.jpg',
                'received_by_name' => 'Chef Ridwan',
                'created_at' => '2026-08-24 10:00:00',
                'updated_at' => '2026-08-25 15:00:00',
            ],
            // Order 6: Grand Pangrango Settled Inflow (SJ-011)
            [
                'id' => 6,
                'order_number' => 'ORD-GPA-202608-0011',
                'user_id' => 9,
                'invoice_id' => 6,
                'order_source' => 'WEB_PORTAL',
                'target_delivery_date' => '2026-08-28',
                'delivery_address' => 'Grand Pangrango Bogor',
                'estimated_total' => 107980000.00,
                'grand_total' => 107980000.00,
                'status' => 'SELESAI',
                'verified_by' => 2,
                'surat_jalan_number' => 'SJ-011',
                'driver_id' => 7,
                'vehicle_plate_number' => 'D 8124 AB',
                'departure_time' => '2026-08-28 05:00:00',
                'arrival_time' => '2026-08-28 08:15:00',
                'pod_photo_url' => 'pod/pod_sj_011.jpg',
                'received_by_name' => 'Suryana',
                'created_at' => '2026-08-27 11:00:00',
                'updated_at' => '2026-08-28 16:00:00',
            ],
            // Order 7: Dapur Sunda Settled Inflow (SJ-012)
            [
                'id' => 7,
                'order_number' => 'ORD-GPA-202609-0012',
                'user_id' => 13,
                'invoice_id' => 7,
                'order_source' => 'WEB_PORTAL',
                'target_delivery_date' => '2026-09-12',
                'delivery_address' => 'Jl. Dr. Setiabudi No. 102 Bandung',
                'estimated_total' => 80180000.00,
                'grand_total' => 80180000.00,
                'status' => 'SELESAI',
                'verified_by' => 2,
                'surat_jalan_number' => 'SJ-012',
                'driver_id' => 6,
                'vehicle_plate_number' => 'B 9014 KPA',
                'departure_time' => '2026-09-12 06:00:00',
                'arrival_time' => '2026-09-12 07:30:00',
                'pod_photo_url' => 'pod/pod_sj_012.jpg',
                'received_by_name' => 'Ibu Ratna',
                'created_at' => '2026-09-11 12:00:00',
                'updated_at' => '2026-09-12 14:00:00',
            ],
            // Order 8: AEON Settled Inflow (SJ-013)
            [
                'id' => 8,
                'order_number' => 'ORD-GPA-202609-0013',
                'user_id' => 14,
                'invoice_id' => 8,
                'order_source' => 'WEB_PORTAL',
                'target_delivery_date' => '2026-09-20',
                'delivery_address' => 'AEON Mall BSD Store',
                'estimated_total' => 74010000.00,
                'grand_total' => 74010000.00,
                'status' => 'SELESAI',
                'verified_by' => 2,
                'surat_jalan_number' => 'SJ-013',
                'driver_id' => 6,
                'vehicle_plate_number' => 'B 9014 KPA',
                'departure_time' => '2026-09-20 05:00:00',
                'arrival_time' => '2026-09-20 08:30:00',
                'pod_photo_url' => 'pod/pod_sj_013.jpg',
                'received_by_name' => 'Dewi Anggraeni',
                'created_at' => '2026-09-19 14:00:00',
                'updated_at' => '2026-09-20 16:00:00',
            ],
            // Order 9: Order Aktif Dalam Pengiriman
            [
                'id' => 9,
                'order_number' => 'ORD-GPA-202610-0099',
                'user_id' => 15, // Pak Hendra (Reguler)
                'invoice_id' => null,
                'order_source' => 'WHATSAPP_ADMIN',
                'target_delivery_date' => now()->toDateString(),
                'delivery_address' => 'Jl. Buah Batu No. 142 Bandung',
                'estimated_total' => 4500000.00,
                'grand_total' => 4500000.00,
                'status' => 'DALAM_PENGIRIMAN',
                'verified_by' => 2,
                'surat_jalan_number' => 'SJ-099',
                'driver_id' => 7,
                'vehicle_plate_number' => 'D 8124 AB',
                'departure_time' => now()->setTime(6, 0),
                'arrival_time' => null,
                'pod_photo_url' => null,
                'received_by_name' => null,
                'created_at' => now()->subDay(),
                'updated_at' => now(),
            ],
        ]);

        // =====================================================================
        // 7. SEED ORDER ITEMS (Rincian Bobot Tera Sah Metrologi)
        // =====================================================================
        DB::table('order_items')->insert([
            // Order 1: Aerofood ACS (Selada Romaine: 10080 kg tera sah)
            [
                'id' => 1,
                'order_id' => 1,
                'product_id' => 1,
                'ordered_qty' => 8000.00,
                'unit_price' => 14275.00,
                'actual_net_weight' => 8000.00,
                'subtotal_final' => 114200000.00,
                'weighed_by' => 4,
                'weighed_at' => now()->subDays(2)->setTime(4, 0),
                'returned_weight' => 0.00,
                'return_reason' => null,
                'created_at' => now()->subDays(4),
                'updated_at' => now()->subDays(2),
            ],
            // Order 2: Grand Pangrango (Tomat Beef: 3970 kg)
            [
                'id' => 2,
                'order_id' => 2,
                'product_id' => 3,
                'ordered_qty' => 4000.00,
                'unit_price' => 15000.00,
                'actual_net_weight' => 3970.00,
                'subtotal_final' => 59550000.00,
                'weighed_by' => 4,
                'weighed_at' => now()->subDays(6)->setTime(3, 45),
                'returned_weight' => 30.00,
                'return_reason' => 'Sortir memar ringan di kebun',
                'created_at' => now()->subDays(8),
                'updated_at' => now()->subDays(6),
            ],
            // Order 3: PT Boga Rasa (Brokoli Super: 2702 kg)
            [
                'id' => 3,
                'order_id' => 3,
                'product_id' => 2,
                'ordered_qty' => 2700.00,
                'unit_price' => 21000.00,
                'actual_net_weight' => 2702.38,
                'subtotal_final' => 56750000.00,
                'weighed_by' => 4,
                'weighed_at' => now()->subDays(10)->setTime(3, 15),
                'returned_weight' => 0.00,
                'return_reason' => null,
                'created_at' => now()->subDays(12),
                'updated_at' => now()->subDays(10),
            ],
            // Order 4: Segar Makmur (Kol Putih: 2400 kg)
            [
                'id' => 4,
                'order_id' => 4,
                'product_id' => 5,
                'ordered_qty' => 2400.00,
                'unit_price' => 7500.00,
                'actual_net_weight' => 2400.00,
                'subtotal_final' => 18000000.00,
                'weighed_by' => 4,
                'weighed_at' => now()->subDays(20)->setTime(4, 30),
                'returned_weight' => 0.00,
                'return_reason' => null,
                'created_at' => now()->subDays(22),
                'updated_at' => now()->subDays(20),
            ],
            // Order 5: Aerofood Settled Inflow (Selada Romaine: 10080 kg)
            [
                'id' => 5,
                'order_id' => 5,
                'product_id' => 1,
                'ordered_qty' => 10200.00,
                'unit_price' => 14500.00,
                'actual_net_weight' => 10080.00,
                'subtotal_final' => 146160000.00,
                'weighed_by' => 4,
                'weighed_at' => '2026-08-25 03:30:00',
                'returned_weight' => 120.00,
                'return_reason' => 'Deviasi susut sortir gudang -1.18%',
                'created_at' => '2026-08-24 10:00:00',
                'updated_at' => '2026-08-25 15:00:00',
            ],
            // Order 6: Grand Pangrango Settled Inflow (Tomat Beef: 6748 kg)
            [
                'id' => 6,
                'order_id' => 6,
                'product_id' => 3,
                'ordered_qty' => 6800.00,
                'unit_price' => 16000.00,
                'actual_net_weight' => 6748.75,
                'subtotal_final' => 107980000.00,
                'weighed_by' => 4,
                'weighed_at' => '2026-08-28 04:00:00',
                'returned_weight' => 51.25,
                'return_reason' => 'Sortir standar hotel bintang lima',
                'created_at' => '2026-08-27 11:00:00',
                'updated_at' => '2026-08-28 16:00:00',
            ],
            // Order 7: Dapur Sunda Settled Inflow (Brokoli: 3644 kg + Kol: 2000 kg)
            [
                'id' => 7,
                'order_id' => 7,
                'product_id' => 2,
                'ordered_qty' => 3644.54,
                'unit_price' => 22000.00,
                'actual_net_weight' => 3644.54,
                'subtotal_final' => 80180000.00,
                'weighed_by' => 4,
                'weighed_at' => '2026-09-12 05:00:00',
                'returned_weight' => 0.00,
                'return_reason' => null,
                'created_at' => '2026-09-11 12:00:00',
                'updated_at' => '2026-09-12 14:00:00',
            ],
            // Order 8: AEON Settled Inflow (Stroberi: 2960 pack)
            [
                'id' => 8,
                'order_id' => 8,
                'product_id' => 4,
                'ordered_qty' => 3000.00,
                'unit_price' => 25000.00,
                'actual_net_weight' => 2960.40,
                'subtotal_final' => 74010000.00,
                'weighed_by' => 4,
                'weighed_at' => '2026-09-20 04:00:00',
                'returned_weight' => 39.60,
                'return_reason' => 'Mika retak penataan cold chain',
                'created_at' => '2026-09-19 14:00:00',
                'updated_at' => '2026-09-20 16:00:00',
            ],
            // Order 9: Reguler (Selada: 300 kg)
            [
                'id' => 9,
                'order_id' => 9,
                'product_id' => 1,
                'ordered_qty' => 300.00,
                'unit_price' => 15000.00,
                'actual_net_weight' => 300.00,
                'subtotal_final' => 4500000.00,
                'weighed_by' => 4,
                'weighed_at' => now()->setTime(5, 30),
                'returned_weight' => 0.00,
                'return_reason' => null,
                'created_at' => now()->subDay(),
                'updated_at' => now(),
            ],
        ]);

        // =====================================================================
        // 8. SEED PAYMENTS (Pelunasan Pembayaran Realisasi Kas)
        // =====================================================================
        DB::table('payments')->insert([
            // Pelunasan Invoice 5 (Aerofood) via Transfer Mandiri Korporat
            [
                'id' => 1,
                'order_id' => 5,
                'invoice_id' => 5,
                'payment_reference' => 'TRF-MND-20260925-8812',
                'payment_method' => 'TRANSFER_BANK',
                'amount' => 146160000.00,
                'proof_url' => 'payments/bukti_transfer_aerofood.pdf',
                'status' => 'LUNAS',
                'verified_by' => 2,
                'paid_at' => '2026-09-25 10:00:00',
                'verification_note' => 'Dana tervalidasi masuk rekening Mandiri Koperasi GPA. Kliring lunas.',
                'created_at' => '2026-09-25 10:00:00',
                'updated_at' => '2026-09-25 10:00:00',
            ],
            // Pelunasan Invoice 6 (Grand Pangrango) via BNI Virtual Account
            [
                'id' => 2,
                'order_id' => 6,
                'invoice_id' => 6,
                'payment_reference' => 'VA-BNI-20260928-3319',
                'payment_method' => 'TRANSFER_BANK',
                'amount' => 107980000.00,
                'proof_url' => 'payments/bukti_va_grandpangrango.pdf',
                'status' => 'LUNAS',
                'verified_by' => 2,
                'paid_at' => '2026-09-28 11:00:00',
                'verification_note' => 'Kliring BNI Virtual Account otomatis H+0.',
                'created_at' => '2026-09-28 11:00:00',
                'updated_at' => '2026-09-28 11:00:00',
            ],
            // Pelunasan Invoice 7 (Dapur Sunda) via Transfer BCA
            [
                'id' => 3,
                'order_id' => 7,
                'invoice_id' => 7,
                'payment_reference' => 'TRF-BCA-20260929-9941',
                'payment_method' => 'TRANSFER_BANK',
                'amount' => 80180000.00,
                'proof_url' => 'payments/bukti_bca_dapursunda.pdf',
                'status' => 'LUNAS',
                'verified_by' => 2,
                'paid_at' => '2026-09-29 14:00:00',
                'verification_note' => 'Verifikasi dua arah rekening koran BCA tuntas.',
                'created_at' => '2026-09-29 14:00:00',
                'updated_at' => '2026-09-29 14:00:00',
            ],
            // Pelunasan Invoice 8 (AEON) via Transfer BCA Korporat
            [
                'id' => 4,
                'order_id' => 8,
                'invoice_id' => 8,
                'payment_reference' => 'TRF-BCA-20260930-1092',
                'payment_method' => 'TRANSFER_BANK',
                'amount' => 74010000.00,
                'proof_url' => 'payments/bukti_aeon_september.pdf',
                'status' => 'LUNAS',
                'verified_by' => 2,
                'paid_at' => '2026-09-30 16:00:00',
                'verification_note' => 'Pelunasan faktur konsolidasi ritel modern AEON tuntas.',
                'created_at' => '2026-09-30 16:00:00',
                'updated_at' => '2026-09-30 16:00:00',
            ],
        ]);
    }
}
